### ISSUE TITLE
Installation issue with opendr

### ISSUE THREAD

**Issue by 5uryansh** [farazBhatti/Human-Body-Measurements-using-Computer-Vision#46]
I'm not able to install opendr (requirements.txt), I am using Python=3.7 version.

**Comment by XTard** [comment]
Me too, even prior to this step - I had to do `pip install protobuf==3.20.1` (suggested by an error while installing requirements.txt).

I am now trying to manually install opendr by `pip install opendr`, but I get the following, although I have MV C++ 14 and greater versions.
```
error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for opendr
  Running setup.py clean for opendr
Failed to build opendr
ERROR: Could not build wheels for opendr, which is required to install pyproject.toml-based projects
```

**Comment by XTard** [comment]
I realized the issue with opendr by running `py -3.7 inference.py -i .\image_1_50.png -ht 180`

And getting the following error:
```
Traceback (most recent call last):
  File "inference.py", line 15, in <module>
    from demo import main
  File "C:\Users\...\Human-Body-Measurements-using-Computer-Vision-master\demo.py", line 30, in <module>
    from src.util import renderer as vis_util
  File "C:\Users\...\Human-Body-Measurements-using-Computer-Vision-master\src\util\renderer.py", line 12, in <module>
    from opendr.camera import ProjectPoints
ModuleNotFoundError: No module named 'opendr'
```

**Comment by jpcurbelo** [comment]
Hi all. In case you are interested, you might take a look [at my repo](https://github.com/jpcurbelo/human-body-reshape-DL-paper) and [paper](https://link.springer.com/article/10.1007/s11042-023-17947-6). Thanks.

**Comment by hamzakhalil798** [comment]
@5uryansh please refer to  https://github.com/farazBhatti/Human-Body-Measurements-using-Computer-Vision/issues/28
